"""
Role-based AI Agents for Tiny-Council.
Each agent represents a specialized perspective in the decision process.
"""

from abc import ABC, abstractmethod
import re
from typing import Dict, List, Any, Optional
try:
    from .llm_backend import BaseLLMBackend, HeuristicRuleEngine
except ImportError:
    import sys
    from pathlib import Path
    PROJECT_ROOT = Path(__file__).resolve().parents[1]
    if str(PROJECT_ROOT) not in sys.path:
        sys.path.insert(0, str(PROJECT_ROOT))
    from tiny_council.llm_backend import BaseLLMBackend, HeuristicRuleEngine


class BaseAgent(ABC):
    """
    Abstract Base Class for AI Council Agents.
    """

    def __init__(
        self,
        name: str,
        role: str,
        persona_description: str,
        weight: float = 1.0,
        temperature: float = 0.7,
        backend: Optional[BaseLLMBackend] = None,
    ):
        self.name = name
        self.role = role
        self.persona_description = persona_description
        self.weight = max(0.1, float(weight))
        self.temperature = temperature
        self.backend = backend or HeuristicRuleEngine()

    def get_system_prompt(self) -> str:
        """Construct system prompt defining agent persona and perspective."""
        pass

    def evaluate_topic(self, topic: str, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Generate initial proposal for given topic."""
        sys_prompt = self.get_system_prompt()
        user_prompt = f"Evaluate topic and provide your structured position:\nTopic: {topic}"
        if context:
            user_prompt += f"\nContext: {context}"

        response_text = self.backend.generate_response(
            sys_prompt, user_prompt, temperature=self.temperature
        )
        confidence = self._extract_confidence(response_text)

        return {
            "agent_name": self.name,
            "role": self.role,
            "weight": self.weight,
            "response": response_text,
            "confidence": confidence,
        }

    def critique_peers(self, topic: str, peer_proposals: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Critique proposals generated by peer agents."""
        sys_prompt = self.get_system_prompt()
        proposals_summary = "\n".join(
            [f"- {p['agent_name']} ({p['role']}): {(p.get('refined_response') or p.get('response', ''))[:200]}..." for p in peer_proposals]
        )
        user_prompt = (
            f"Critique peer proposals for topic: '{topic}'. Identify flaws, assumptions, or gaps:\n"
            f"{proposals_summary}"
        )
        response_text = self.backend.generate_response(
            sys_prompt, user_prompt, temperature=self.temperature
        )

        return {
            "agent_name": self.name,
            "role": self.role,
            "critique": response_text,
        }

    def refine_position(
        self, topic: str, initial_response: str, critiques: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """Refine position after considering peer critiques."""
        sys_prompt = self.get_system_prompt()
        critique_summary = "\n".join(
            [f"- {c['agent_name']}: {c['critique'][:150]}..." for c in critiques]
        )
        user_prompt = (
            f"Topic: '{topic}'\nYour Initial Response: {initial_response}\n"
            f"Peer Critiques Received:\n{critique_summary}\n"
            f"Provide your revised position and updated confidence score."
        )
        response_text = self.backend.generate_response(
            sys_prompt, user_prompt, temperature=self.temperature
        )
        confidence = self._extract_confidence(response_text)

        return {
            "agent_name": self.name,
            "role": self.role,
            "weight": self.weight,
            "refined_response": response_text,
            "confidence": confidence,
        }

    def _extract_confidence(self, text: str) -> float:
        """Parse numerical confidence score from response text."""
        match = re.search(r"confidence(?: score)?:?\s*(0\.\d+|1\.0|\d{1,3}%?)", text, re.IGNORECASE)
        if match:
            val_str = match.group(1).rstrip("%")
            val = float(val_str)
            if val > 1.0:
                val /= 100.0
            return max(0.0, min(1.0, val))
        return 0.80  # Default confidence fallback


class AnalystAgent(BaseAgent):
    """Analyst focusing on quantitative evidence, metrics, and technical feasibility."""

    def __init__(self, name: str = "Dr. Data", weight: float = 1.2, backend: Optional[BaseLLMBackend] = None):
        super().__init__(
            name=name,
            role="Analyst",
            persona_description="Data-driven technical expert focused on metrics, empirical evidence, and operational risk.",
            weight=weight,
            temperature=0.3,
            backend=backend,
        )

    def get_system_prompt(self) -> str:
        return (
            f"You are {self.name}, an Analyst AI Agent. {self.persona_description} "
            "Deconstruct questions into empirical variables, failure metrics, quantitative feasibility, and KPI impact. "
            "Always include a Confidence score (0.0 to 1.0)."
        )


class CriticAgent(BaseAgent):
    """Critic focusing on stress testing, identifying logical fallacies, and security/safety edge cases."""

    def __init__(self, name: str = "Skeptic-1", weight: float = 1.0, backend: Optional[BaseLLMBackend] = None):
        super().__init__(
            name=name,
            role="Critic",
            persona_description="Devil's advocate and security auditor focused on vulnerabilities, edge cases, and hidden assumptions.",
            weight=weight,
            temperature=0.5,
            backend=backend,
        )

    def get_system_prompt(self) -> str:
        return (
            f"You are {self.name}, a Critic AI Agent. {self.persona_description} "
            "Rigorously challenge proposals, point out flaws, single-points-of-failure, and unverified assumptions. "
            "Always include a Confidence score (0.0 to 1.0)."
        )


class StrategistAgent(BaseAgent):
    """Strategist focusing on long-term vision, trade-offs, and scalability."""

    def __init__(self, name: str = "Architect Prime", weight: float = 1.1, backend: Optional[BaseLLMBackend] = None):
        super().__init__(
            name=name,
            role="Strategist",
            persona_description="Strategic planner focused on long-term scalability, trade-offs, modular design, and execution alignment.",
            weight=weight,
            temperature=0.7,
            backend=backend,
        )

    def get_system_prompt(self) -> str:
        return (
            f"You are {self.name}, a Strategist AI Agent. {self.persona_description} "
            "Evaluate long-term architectural trade-offs, scalability milestones, and strategic agility. "
            "Always include a Confidence score (0.0 to 1.0)."
        )


class EthicsAgent(BaseAgent):
    """Ethics Evaluator focusing on safety, compliance, fairness, and user impact."""

    def __init__(self, name: str = "Aegis", weight: float = 1.0, backend: Optional[BaseLLMBackend] = None):
        super().__init__(
            name=name,
            role="Ethics Evaluator",
            persona_description="Safety & ethics expert evaluating compliance, algorithmic bias, transparency, and human-centric safety.",
            weight=weight,
            temperature=0.4,
            backend=backend,
        )

    def get_system_prompt(self) -> str:
        return (
            f"You are {self.name}, an Ethics & Safety AI Agent. {self.persona_description} "
            "Ensure decisions align with transparency, privacy, bias mitigation, and safety guardrails. "
            "Always include a Confidence score (0.0 to 1.0)."
        )


class SynthesizerAgent(BaseAgent):
    """Synthesizer focusing on aggregating agent assessments and drafting council resolutions."""

    def __init__(self, name: str = "Council Chair", weight: float = 1.0, backend: Optional[BaseLLMBackend] = None):
        super().__init__(
            name=name,
            role="Synthesizer",
            persona_description="Objective council chair responsible for summarizing diverse views, resolving deadlocks, and formulating final action plans.",
            weight=weight,
            temperature=0.3,
            backend=backend,
        )

    def get_system_prompt(self) -> str:
        return (
            f"You are {self.name}, the Council Synthesizer. {self.persona_description} "
            "Synthesize all perspectives into a clear, unified executive resolution."
        )


class CustomAgent(BaseAgent):
    """Custom Agent with user-defined role and system prompt."""

    def __init__(
        self,
        name: str,
        role: str,
        persona_description: str,
        weight: float = 1.0,
        temperature: float = 0.7,
        backend: Optional[BaseLLMBackend] = None,
    ):
        super().__init__(
            name=name,
            role=role,
            persona_description=persona_description,
            weight=weight,
            temperature=temperature,
            backend=backend,
        )

    def get_system_prompt(self) -> str:
        return (
            f"You are {self.name}, a specialized AI Agent with role '{self.role}'. "
            f"{self.persona_description} Always include a Confidence score (0.0 to 1.0)."
        )

if __name__ == "__main__":
    analyst = AnalystAgent()
    res = analyst.evaluate_topic("Test architecture decision")
    print(f"[Self-Test] Agent: {res['agent_name']} | Role: {res['role']} | Confidence: {res['confidence']}")
