# -*- coding: utf-8 -*-
"""GenderPayGap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cm1f33YP_NN5a0IxgiuSLFV1IPs_VaTp
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#for machine learning algorithms
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

import xgboost as xgb
import shap

df=pd.read_csv("gendergapinaverage new.csv")
print(df.head())
print(df.info())

#Advanced preprocessing and Handling missing values

numeric_features = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = df.select_dtypes(include=['object']).columns.tolist()

if "gender_pay_gap" in numeric_features:
    numeric_features.remove("gender_pay_gap")

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

# For time based feature engineering
# global trend index (captures time effect)
df["year_normalized"] = df["Year"] - df["Year"].min()

# decade grouping
df["decade"] = (df["Year"] // 10) * 10

#Country-wise average gap
country_mean = df.groupby("country")["Gender wage gap %"].transform("mean")
df["country_avg_gap"] = country_mean

#Country wise inequality instability over time time
country_std = df.groupby("country")["Gender wage gap %"].transform("std")
df["country_gap_volatility"] = country_std

# Frequency Encoding for every country
code_freq = df["Code"].value_counts()
df["code_frequency"] = df["Code"].map(code_freq)

# Trend detecting feature to analyse if the gap is increasing or decreasing with time for every country
df["country_year_trend"] = df.groupby("country")["Gender wage gap %"].transform(
    lambda x: x.diff().fillna(0)
)

#Lag feature to check time dependency
df = df.sort_values(["country", "Year"])

df["gap_lag1"] = df.groupby("country")["Gender wage gap %"].shift(1)
df["gap_lag1"] = df["gap_lag1"].fillna(df["gap_lag1"].mean())

# Final features set
features = [
    "Year",
    "year_normalized",
    "decade",
    "country_avg_gap",
    "country_gap_volatility",
    "code_frequency",
    "country_year_trend",
    "gap_lag1"
]

X = df[features]
y = df["Gender wage gap %"]

#splitting the data for testing and training based on the year
train = df[df["Year"] < 2010]
test = df[df["Year"] >= 2010]

X_train = train[features]
y_train = train["Gender wage gap %"]

X_test = test[features]
y_test = test["Gender wage gap %"]

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

preprocess = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

model = xgb.XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror"
)

from sklearn.pipeline import Pipeline

final_model = Pipeline([
    ("preprocess", preprocess),
    ("model", model)
])

final_model.fit(X_train, y_train)

preds = final_model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, preds))
print("R2 Score:", r2_score(y_test, preds))

import matplotlib.pyplot as plt

plt.scatter(y_test, preds)
plt.xlabel("Actual Gap")
plt.ylabel("Predicted Gap")
plt.title("Actual vs Predicted Gender Wage Gap")
plt.show()

# Country wise trend over the years
import seaborn as sns

plt.figure(figsize=(10,5))
sns.lineplot(data=df, x="Year", y="Gender wage gap %", hue="country")
plt.title("Gender Wage Gap Trends by Country")
plt.show()

# Heatmap for analysing country vs year trends
pivot_df = df.pivot(
    index="country",
    columns="Year",
    values="Gender wage gap %"
)

plt.figure(figsize=(14,6))
sns.heatmap(pivot_df, cmap="YlOrRd")
plt.title("Gender Wage Gap by Country and Year")
plt.show()

df = df.rename(columns={
    "Gender wage gap %": "gap"
})

# Box plot - when there are are many years per country (sorted acc to median)
country_order = (
    df.groupby("country")["gap"]
      .median()
      .sort_values()
      .index
)

plt.figure(figsize=(12,6))

sns.boxplot(
    data=df,
    x="country",
    y="gap",
    order=country_order
)

plt.title("Gender Wage Gap Distribution by Country")
plt.xlabel("Country")
plt.ylabel("Gender Wage Gap (%)")

plt.xticks(rotation=45)

plt.tight_layout()
plt.show()