language: "en_core_web_md"

pipeline:
  - name: "nlp_spacy" # loads the spacy language model
  - name: "tokenizer_spacy" # splits the sentence into tokens
  - name: "ner_crf" # uses the pretrained spacy NER model
  - name: "intent_featurizer_spacy" # transform the sentence into a vector representation
  - name: "intent_classifier_sklearn" # uses the vector representation to classify using SVM
  - name: "ner_synonyms" # trains the synonyms

policies:
  - name: "RulePolicy"
    # Confidence threshold for the `core_fallback_action_name` to apply.
    # The action will apply if no other action was predicted with
    # a confidence >= core_fallback_threshold
    core_fallback_threshold: 0.68
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
