# -*- coding: utf-8 -*-
"""Facial_detection_using_DeepLearning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t9OgAkV_U2cVO3J2mszZzTvibf9Cc-nB
"""

# import required modules
import tensorflow as tf

!pip install mtcnn

import cv2
from mtcnn.mtcnn import MTCNN
from google.colab.patches import cv2_imshow
!curl -o logo.png https://colab.research.google.com/img/colab_favicon_256px.png

#read the file
image_file="/content/image1.jpg"
image=cv2.imread(image_file)

# function for detecting the faces and building a rectangle over the face
def face_detection(image):
  # resize the images
  w=int(image.shape[1]/2)
  h=int(image.shape[0]/2)
  image=cv2.resize(image,(w,h),interpolation = cv2.INTER_AREA)
  # detection of faces
  detector=MTCNN()
  faces=detector.detect_faces(image)
  print("\n")
  # locate the faces by drawing the boxes around them
  print("After detecting the faces:\n")
  for face in faces:
    x,y,w,h=face['box']
    cv2.rectangle(image,(x,y),((w+x),(h+y)),(255,0,0),2)
  cv2_imshow(image)

face_detection(image)

# testing the function on another image
print("Testing the function with other images:")
image="/content/image2.jpg"
face_detection(cv2.imread(image))