name: Build README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '5 * * * *'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Update README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |-
        python build_readme.py
        cat README.md
    - name: Commit and push (if changed)
      run: |-
        git diff
        git config --global user.name "readme-bot"
        git config --global user.email "actions@users.noreply.github.com"
        git add README.md
        git commit -m "This is an automated update of README.md." || exit 0
        git push
